class MoodTips {
  static final Map<int, List<String>> _tips = {
    0: [ // Happy 😊
      "Keep smiling! It brightens your day.",
      "Share your happiness with someone today.",
      "Celebrate small wins today.",
      "Write down three things you’re grateful for.",
      "Take a moment to appreciate your surroundings.",
      "Listen to your favorite upbeat song.",
      "Give a compliment to someone.",
      "Do something creative, like drawing or doodling.",
      "Spend time outdoors and enjoy the sunshine.",
      "Dance to your favorite tune for a few minutes.",
      "Help someone else—it boosts your mood too.",
      "Take a few deep breaths and savor the moment.",
      "Reflect on a happy memory today.",
      "Enjoy a small treat or snack you love.",
      "Read something inspiring or funny.",
      "Connect with a friend and share a laugh.",
      "Do a simple act of kindness.",
      "Write down a positive affirmation.",
      "Try a short meditation focused on gratitude.",
      "Smile at yourself in the mirror.",
      "Cook or bake something fun.",
      "Celebrate a recent accomplishment.",
      "Take a short walk and notice small joys.",
      "Watch a funny video or show.",
      "Spend a few minutes in quiet reflection.",
      "Listen to nature sounds or relaxing music.",
      "Give yourself a small reward for today’s efforts.",
      "Look at photos that make you happy.",
      "Compliment someone genuinely.",
      "Take a moment to breathe and feel good."
    ],
    1: [ // Tired 😴
      "Take a short break or power nap.",
      "Hydrate and relax for a few minutes.",
      "Stretch your body gently.",
      "Listen to calming music.",
      "Close your eyes and take deep breaths.",
      "Step outside for a quick walk.",
      "Drink a cup of tea or coffee if needed.",
      "Do a few light exercises to boost energy.",
      "Avoid screens for a few minutes.",
      "Rest your eyes and mind.",
      "Take slow, deep breaths to refresh.",
      "Organize your workspace a little.",
      "Write down tasks to clear your mind.",
      "Try a short guided meditation.",
      "Eat a light, healthy snack.",
      "Stand up and move around for a few minutes.",
      "Allow yourself 5 minutes of complete rest",
      "Take a few moments to stretch your neck and shoulders.",
      "Step into sunlight briefly.",
      "Sit quietly and focus on your breath.",
      "Try a short visualization of energy.",
      "Drink a glass of water slowly.",
      "Smile—it can refresh your mood.",
      "Focus on one simple task at a time.",
      "Take a moment to notice your surroundings.",
      "Practice a few shoulder rolls or stretches.",
      "Write down one small goal for the day.",
      "Listen to uplifting podcasts or music.",
      "Step outside and breathe fresh air.",
      "Take a few minutes to relax without multitasking.",
      "Recall a recent happy memory to boost energy."
    ],
    2: [ // Anxious 😰
      "Try deep breathing for 5 minutes.",
      "Limit news or social media for a while",
      "Write down what's worrying you to release your mind.",
      "Focus on one task at a time.",
      "Take a short walk to clear your head.",
      "Listen to calming music or nature sounds.",
      "Stretch your body to release tension.",
      "Practice a grounding exercise: notice 5 things you see.",
      "Drink a glass of water slowly.",
      "Write down positive affirmations.",
      "Take slow, deep breaths and count to 10.",
      "Sit quietly and observe your thoughts without judgment.",
      "Write down your worries and set them aside.",
      "Step outside and notice your surroundings.",
      "Do a short meditation or mindfulness exercise.",
      "Talk to a trusted friend or family member.",
      "Visualize a peaceful, safe place.",
      "Limit caffeine or sugar for a while.",
      "Listen to a calming podcast or audiobook.",
      "Move gently—stretch, walk, or yoga.",
      "Focus on sensations in your body to ground yourself.",
      "Write down 3 things you are grateful for.",
      "Try a short progressive muscle relaxation exercise.",
      "Repeat a calming mantra silently.",
      "Take a few minutes away from screens.",
      "Do a small, simple task to regain focus.",
      "Draw or color to relax your mind.",
      "Notice your breathing pattern and slow it down.",
      "Smile or do a gentle laugh—it can help reduce tension.",
      "Take a few deep breaths and acknowledge your feelings.",
      "Reflect on something that went well today.",
      "Remind yourself that anxiety is temporary."
    ],
    3: [ // Angry 😡
      "Take a few deep breaths and count to 10.",
      "Channel energy into exercise (running, pushups)",
      "Step away for a short walk to cool down.",
      "Listen to calming music or do a short meditation.",
      "Write down what is making you angry.",
      "Stretch or do light exercises to release tension.",
      "Drink a glass of water slowly.",
      "Focus on a neutral or positive image in your mind.",
      "Practice deep breathing exercises.",
      "Talk to someone you trust to vent safely.",
      "Step outside and get some fresh air.",
      "Do a short mindfulness exercise.",
      "Listen to a calming podcast or audio.",
      "Write down three things you are grateful for.",
      "Squeeze a stress ball or do a physical release.",
      "Take a moment to pause before responding.",
      "Visualize letting go of the anger.",
      "Focus on something you enjoy for a few minutes.",
      "Write a letter to release your feelings (don’t send it).",
      "Do a quick physical activity like jumping jacks.",
      "Take a shower or wash your face to reset.",
      "Practice progressive muscle relaxation.",
      "Repeat a calming phrase or mantra.",
      "Engage in a creative activity like drawing.",
      "Reflect on something that went well today.",
      "Listen to gentle nature sounds.",
      "Count slowly from 1 to 20 while breathing deeply.",
      "Write down positive affirmations.",
      "Talk to a counselor or supportive friend.",
      "Take a few minutes of quiet reflection.",
      "Remind yourself that feelings pass with time."
    ],
    4: [ // Sad 😔
      "It’s okay to feel sad. Try journaling your thoughts.",
      "Take a short walk or listen to calming music.",
      "Talk to someone you trust.",
      "Allow yourself to cry — it’s healing",
      "Write down one thing that made you smile today.",
      "Practice deep breathing for a few minutes.",
      "Watch something uplifting or funny.",
      "Do a small act of self-care.",
      "Listen to relaxing music or nature sounds.",
      "Draw or doodle your feelings.",
      "Write down one thing you’re grateful for.",
      "Call or text a friend for support.",
      "Sit quietly and focus on your breath.",
      "Take a warm shower or bath.",
      "Stretch gently to release tension.",
      "Read a comforting book or story.",
      "Spend time with a pet if you have one.",
      "Go outside and notice nature.",
      "Write down your worries and release them.",
      "Give yourself permission to rest.",
      "Reflect on something you accomplished recently.",
      "Try a short meditation or relaxation exercise.",
      "Listen to an inspiring podcast.",
      "Write down positive affirmations.",
      "Do something creative or crafty.",
      "Focus on one small task to regain control.",
      "Enjoy a favorite snack mindfully.",
      "Take a few moments to just breathe.",
      "Visualize a peaceful scene in your mind.",
      "Reach out to a supportive friend or family member.",
      "Give yourself a hug or gentle touch.",
      "Remind yourself that emotions are temporary."
    ],
  };

  /// Get a random tip for a given mood index
  static String getTip(int moodIndex) {
    final tips = _tips[moodIndex] ?? ["Take care of yourself today 🌱"];
    tips.shuffle();
    return tips.first;
  }
}
